### ISSUE TITLE
Divs vs semantic html (articles, etc)

### ISSUE THREAD

**Issue by sbinlondon** [fac-14/IJKL-Team-Site#44]
https://github.com/fac-14/IJKL-Team-Site/blob/7d3135c79171014a4104cdd6b259fa7a34c56b3d/index.html#L66

I'm interested to know about your decisions to use high level semantic HTML (sections) but not other things like 'article' or 'figure'. Could you explain a bit more about your process - was this a decision made by the team or is this just how it happened? More of a question than an issue 😃

**Comment by developess** [comment]
We didn't think anything really constituted stand-alone content (blog post, widget etc) which is why we hardly used article tags! 

We felt the images (headshots) were sufficiently semantically conveyed with 'img' tags since they were more decorative - not referenced in the text or essential to understanding the document.
